---
ID: "c43e0b86-8bb7-4fde-b3fa-6a7fe927a02e"
Parent: "06d62338-e11c-42ac-83f6-42f7a14b2b87"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/SitecoreCinema/Feature/SitecoreCinema/Concession/ConcessionProduct/Product Name
DB: master
SharedFields:
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: "Single-Line Text"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210426T024532Z
