---
ID: "4a9913fa-03b6-4f34-86aa-f7d9e46f6f35"
Parent: "29af8be5-3e25-4cce-9d14-c5e9530ea81f"
Template: "29af8be5-3e25-4cce-9d14-c5e9530ea81f"
Path: /sitecore/templates/Feature/GatedContent/Gated Form/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210611T182202Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
